name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    name: Check linting & formatting 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup UV
        uses: astral-sh/setup-uv@v7
        with:
          uv-version: latest
          enable-cache: true

      - name: Run linter
        run: uvx ruff check . --output-format=github

      - name: Run formatter
        run: uvx ruff format . --check 